DM-21003: Take another look at pex_exceptions hierarchy
lsst/pex_exceptions pull request #24
Opened 2019-08-19 20:08 UTC by timj

2019-08-23 20:11 UTC, ktlim requested changes
I'm OK with the additions of `builtins`, which I think are clarifying and should not change things.  I am not so OK with the changing of `(lsst.pex.exceptions.)RuntimeError` to `(lsst.pex.exceptions.)Exception` as a base class for several errors unless a clear usage problem is given as a test case (not just a "did the code do what I said" test case as is currently present).

2019-08-23 20:11 UTC, ktlim commented on python/lsst/pex/exceptions/wrappers.py
> +class LogicError(Exception, builtins.Exception):
Isn't `builtins.Exception` already a base of `Exception`?

2019-08-23 20:11 UTC, ktlim commented on python/lsst/pex/exceptions/wrappers.py
> +class OverflowError(Exception, builtins.OverflowError):
I thought the intent here was to replicate the C++ inheritance hierarchy on the left and the Python one on the right.  In C++, `overflow_error` does derive from `runtime_error`.

2019-08-26 15:59 UTC, timj commented on python/lsst/pex/exceptions/wrappers.py
> +class OverflowError(Exception, builtins.OverflowError):
Yes, now I'm not entirely sure what @brianv0 's problem really is. This ticket only really changes `UnderflowError`, `OverFlowError` and `IoError`, yet I thought @brianv0 was seeing a problem with `NotFoundError`, which is only changing here with the addition of an explicit `builtins`.  I'll repush this ticket without the `RuntimeError` changes and ask him to test it.

2019-08-28 06:37 UTC, ktlim approved these changes

2019-08-28 16:52 UTC, merged